builds:
- id: kspan
  main: . # in Dockerfile, this was renamed /manager and made the entrypoint
  flags:
  - -a # force rebuilding of packages already up-to-date
defaultPlatforms:
- linux/arm64
- linux/amd64
