---
name: Ko
on: [pull_request, create]  # create is for tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - uses: golangci/golangci-lint-action@v2
      with:
          version: latest
          args: --timeout=5m

    - run: make test

    - uses: ko-build/setup-ko@v0.6
    - if: github.ref_type == 'branch' && github.ref_name ==  'main'
      run: ko build -B
    - if: github.ref_type == 'tag'
      run: |
        export KO_DOCKER_REPO=ghcr.io/tylerhelmuth/kspan
        ko build -B --tags "latest,$(echo ${{ github.ref }} | cut -c11-)"

