---
name: Ko

on: [push, pull_request, create]  # create is for tags

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - uses: golangci/golangci-lint-action@v2
      with:
          version: latest
          args: --timeout=5m

    - run: make test

    - uses: ko-build/setup-ko@v0.6
    - run: ko build --platform=linux/amd64,linux/arm64
